### ISSUE TITLE
Add benchmark to detect performance regressions

### ISSUE THREAD

**Issue by gliwka** [gliwka/hyperscan-java#1]

**Comment by gliwka** [comment]
The best thing would be to operate on the same corpora the native hyperscan benchmark tool hsbench is operating on, see https://01.org/blogs/jpviiret/2017/performance-analysis-hyperscan-hsbench

**Comment by toddleo** [comment]
I can't help to notice that *hyperscan-java* is an order of magnitude **slower** in my use case. Hence I created my test cases (not the same corpora of hyperscan benchmark though), to see if there's room for improvements. [Here](https://github.com/toddleo/hyperscan-java#benchmark)'s how to use my benchmark.

**Comment by gliwka** [comment]
@toddleo can you describe your use case and provide an example on how you attempt to use hyperscan-java in a new issue? It's not clear to me from your "benchmark code" what your exact use case is.

Furthermore, it's advisable to use a benchmark framework like JMH (see [here](https://blog.codecentric.de/en/2017/10/performance-measurement-with-jmh-java-microbenchmark-harness/) for an introduction), because JVM benchmarking is hard to get right.

**Comment by toddleo** [comment]
@gliwka you are right *scalatest* might not be the proper tool for benchmark. I'll see what I can do with [sbt-jmh](https://github.com/ktoso/sbt-jmh) (or maybe [ScalaMeter](http://scalameter.github.io/)) in the following days, and update description for my use case.

Nevertheless, happy new year! :fireworks:
