### ISSUE TITLE
logical combination of expressions

### ISSUE THREAD

**Issue by csyzhang** [gliwka/hyperscan-java#106]
@gliwka excellent wrapper. I like it. Thanks a lot for your contribution. 
When I use the hyperscan-java library, I need to do regular expression combinations. I see the native hyperscan support it (https://software.intel.com/content/www/us/en/develop/articles/logical-combinations-of-regular-expressions-in-hyperscan.html). I am wondering how to achieve this in this java binding? 

another question is that in native hyperscan, each expression can be set with an id, is it similar to the context in hyperscan-java?

Thanks!

**Comment by gliwka** [comment]
There is basic support for combinations:
https://github.com/gliwka/hyperscan-java/blob/main/src/test/java/com/gliwka/hyperscan/wrapper/IntegrationTest.java#L241

The ID  is the position of the expression in the list (first expression = 0, second expression = 1 etc.). If it helps, I can add functionality to specify custom IDs.

An alternative could be a nice DSL to describe the combinations, but I don't have the time to implement this.

**Comment by csyzhang** [comment]
Thanks a lot for the reply @gliwka. It would be great if we can specify custom IDs explicitly. It will be easy to identity and manage expressions when the number of expressions increases.

**Comment by csyzhang** [comment]
@gliwka , two more questions - 

1. could you please show an example of how to use the "context" field in expression? 
2. after scan, I get a list of matches. But how do I know which expressions are matched? looks there is no method to return the matched expression ID. what I can do is to get the matched expression string by using match.getMatchedExpression().getExpression() and look up from the original expression list to find our which expression get matched. Is there any other better approaches? 

Appreciated!

**Comment by gliwka** [comment]
@csyzhang You can call getMatchedExpression() on the Match. Instead of the id, this will return the matching expression object directly.

Some pseudo-code for illustration:
```java
Expression appleExpression = new Expression("apple"));
Expression cucumberExpression = new Expression("cucumber"));

List<Expression> expressions = new ArrayList<>();
expressions.add(apple);
expressions.add(cucumber);

Database db = Database.compile(expressions);
scanner.allocScratch(db);

List<Match> matches = scanner.scan("I've got an apple");
assert(matches.get(0).getMatchedExpression() == appleExpression);
```

The context-field allows you to attach an object of your choice to an expression. You can use it to map between the expression and some object in your codebase. For example:

```java
SomeClass someObject = new SomeClass();
Expression someExpression = new Expression("expression", sombeObject);

...

List<Match> matches = scanner.scan("expression");
assert(matches.get(0).getMatchedExpression().getContext() == someObject);
```

**Comment by gliwka** [comment]
I will add some logic to allow for custom id's and will expose the id in the Expression class.
