### ISSUE TITLE
Class Not Found Exception

### ISSUE THREAD

**Issue by vishantakhani** [gliwka/hyperscan-java#127]
I am using the latest version of hyper scan for text scanning.
Getting below error 
java.lang.NoClassDefFoundError: org/bytedeco/javacpp/Pointer

Have gone through the code and found that in com.gliwka.hyperscan.wrapper.Database Pointer is getting used.
Tried after downloading javacpp jars as we but still getting the same error.

Below dependencies i tried with.

		
		<dependency org="com.gliwka.hyperscan" name="hyperscan" rev="5.4.0-2.0.0" transitive="false"/>

		
		<dependency org="org.bytedeco" name="javacpp" rev="1.5.5"/>

		
		<dependency org="org.bytedeco" name="javacpp-platform" rev="1.5.5"/>
		
And tried with 
		
                 
		<dependency org="com.gliwka.hyperscan" name="hyperscan" rev="5.4.0-2.0.0" transitive="true"/>
		
Both time i got same error at "try (Database db = Database.compile(expressions)) {"

Please help me to solve this issue , i tried a lot but not getting any solution.

**Comment by gliwka** [comment]
I assume you're using Apache Ivy as a dependency manager. Unfortunately I'm not familiar with it and thus am unable to help you.

I would suggest you to ask this question on stackoverflow. Using this package with other managers like gradle or maven works fine.

Sorry I can't be of more help.
