### ISSUE TITLE
Apple Silicon support

### ISSUE THREAD

**Issue by gliwka** [gliwka/hyperscan-java#128]
Add support for new Apple M1 Macs by compiling binaries based on one of the hyperscan ARM forks.

**Comment by gliwka** [comment]
@eliaslevy I've seen your comment on the hyperscan ARM thread: https://github.com/intel/hyperscan/issues/197#issuecomment-680264864

Which ARM port if any are you using for Apple Silicon, if any?

**Comment by gliwka** [comment]
The vectorcamp fork doesn't compile on clang:
https://github.com/VectorCamp/vectorscan/issues/21

**Comment by eliaslevy** [comment]
Alas, I've not gone down that route yet, so I can't be of assistance.

**Comment by jhsenjaliya** [comment]
@gliwka , any plan to support ARM (using the ARM variant of hyperscan : https://github.com/VectorCamp/vectorscan) ? This is amazing work btw. Thanks for doing and sharing it.

**Comment by gliwka** [comment]
@jhsenjaliya Yes, will come with the next release. As you already discovered you can use the snapshot release of the natives in the meantime

**Comment by pedroboado** [comment]
Hi @gliwka, thanks for the awesome work. Is there any chance to have a release of `hyperscan-native:1.1.0` and a corresponding new release of `hyperscan-java`?  I've noticed a couple of minor rough edges trying to make it work for us: 
- `hyperscan-java-native:1.1.0-SNAPSHOT` is missing `linux-x86_64` classifier
- We needed to upgrade `org.bytedeco:javacpp` to 1.5.7 for it to run in Apple silicon

I'm happy to help , can you let me know if I can be of help somehow?

**Comment by luengnat** [comment]
I wonder where are we with this. Is there anything I can help?

**Comment by rui-ribeiro** [comment]
@gliwka, Any updates on this feature? If work is needed, can you give a rough list of what still needs to be completec?

**Comment by miro-trifonov** [comment]
Hey, even if this is not going to be released officially, is it possible to run a mac version locally. If so, what do we need to do to enable this?

**Comment by gliwka** [comment]
ARM64 (Apple Silicon) is supported in the latest release.
