### ISSUE TITLE
The Scanner.class has a bug

### ISSUE THREAD

**Issue by xishian** [gliwka/hyperscan-java#134]
The Scanner(com.gliwka.hyperscan.wrapper.Scanner) has a static field `private static int count = 0;`
If many threads consturct the Scanner instance, the value of count cannot be accurate.
Please use AtomicInteger rather than int

**Comment by gliwka** [comment]
Thanks for pointing it out. Will fix this in the next release, which is coming soon. I‘m working on something, which will remove the need to track the number of scanner instances.
