### ISSUE TITLE
java.lang.OutOfMemoryError: Cannot allocate new PointerPointer(13): totalBytes = 0, physicalBytes = 8085M\n\tat org.bytedeco.javacpp.PointerPointer.<init>(PointerPointer.java:149)\n\tat com.gliwka.hyperscan.wrapper.Database.compile(Database.java:83)

### ISSUE THREAD

**Issue by Jtiag** [gliwka/hyperscan-java#149]
try (Database db = Database.compile(expressions);
             Scanner scanner = new Scanner()) {
            scanner.allocScratch(db);
        }

parallel call this method，some time latter in PointerPointer() allocate memory failed

**Comment by gliwka** [comment]
Can you please provide some sample code or a repository to reproduce this?
