### ISSUE TITLE
Database instances not reclaimable by GC

### ISSUE THREAD

**Issue by mmimica** [gliwka/hyperscan-java#161]
Two linked issues:
`NativeDatabase` ctor is not invoked when an instances is created by `hs_compile_multi`, so deallocator is not registered there.

In `com.gliwka.hyperscan.wrapper.Database#load(java.io.InputStream, java.io.InputStream)`, the ctor is called, but the deallocator lambda contains a reference to `ṫhis`, which makes it non-reclaimable by GC.
`this.deallocator(() -> hs_free_database(this));`

**Comment by simpleyetawesomeprojects** [comment]
hello @mmimica , I have a question unrelated to your PR. I'm stuck on a problem and could not solve it. I guess you might have an idea, I have created an issue here https://github.com/gliwka/hyperscan-java-native/issues/29. I would highly appreciate it if you can provide any suggestions on how the issue could be resolved. Thank you in advance and apologies for this unrelated comment.

**Comment by mmimica** [comment]
Sorry, I'm not up to the task. All I know about javacpp I have learned by looking at your code.
