### ISSUE TITLE
Any plans to support linux_arm in the future?

### ISSUE THREAD

**Issue by Gmgge** [gliwka/hyperscan-java#183]
thank you very much for your work

I found hyperscan supported by arm: https://github.com/kunpengcompute/hyperscan

If I want to adapt it myself, should I modify this hyperscan-java-native/build.sh?

If you can give me some advice or ideas, thank you very much

**Comment by gliwka** [comment]
@Gmgge I'm investigating 64-bit ARM support (armv8). Would that be enough for you? I'm currently not considering implementing 32-bit support, you would need to contribute that yourself.

**Comment by Gmgge** [comment]
Thank you for your reply. 64-bit meets the requirements of current mainstream applications.

**Comment by krisso-rtb** [comment]
Would it support Mac M1 ?
