### ISSUE TITLE
utf8 match

### ISSUE THREAD

**Issue by liuhe36** [gliwka/hyperscan-java#2]
Hi,I'm a novice to hyperscan

I have a question whether hyperscan supports matching Chinese characters?

I use your code hyperscan-java and set the expressionFlag to utf-8, but it can't match result.

Examples are as follows：
expression：测试
scan：这是一个测试

thanks.

**Comment by gliwka** [comment]
Hi lihue36,

thanks for the bug report. I'm able to reproduce it. Seems like there's some issues with UTF-8 characters. 

I'll investigate if it's a issue with the JNA wrapper or with hyperscan itself and will come back to you with a solution.

Best,
Matthias

**Comment by gliwka** [comment]
@liuhe36 Sorry it took so long, but i've finally was able to fix the bug. In case of UTF8 characters the code was passing a wrong length of the input data.

I've pushed out version 0.1.1 which fixes the bug by using getBytes().length instead of the length property!

Please try again.

**Comment by liuhe36** [comment]
@gliwka oh,it's exciting, I will try it right now.

**Comment by gliwka** [comment]
Let me know how it goes 😄

**Comment by liuhe36** [comment]
it works well
thanks and I will run a performance benchmark between native hyperscan and yours，so that I can integrate hyperscan-java into my project.

Do you have any advice or Did you run benchmark before?

**Comment by gliwka** [comment]
I'm happy it works for you. Let's continue the discussion about benchmarking in the issue #1
