### ISSUE TITLE
Update to Hyperscan 5.2

### ISSUE THREAD

**Issue by gliwka** [gliwka/hyperscan-java#48]

**Comment by SwiftEngineer** [comment]
I don't know if this helps, but I thought I'd [link my fork of this repo here](https://github.com/SocialIntelligence/hyperscan-java) just in case anyone wanted to try out Chimera right now, or if it maybe could help resolve this issue. In its current state the project is pretty bad, but I can't argue that it doesn't perform well and it is tested.

Should get a lot better over the next week or so, but I would argue that if you just want Hyperscan functionality and don't care about PCRE regexes, https://github.com/LocateTech/hyperscan-java is still your best bet.

**Comment by gliwka** [comment]
@SwiftEngineer Thank you very much for your comment. 

I'm planning on resolving this issue until the end of the year. Your repository looks interesting, would you mind me selectively integrating your work in hyperscan-java?

**Comment by gliwka** [comment]
Contributor access would also be an option.

**Comment by SwiftEngineer** [comment]
Of course! Grab whatever code you'd like from the chimera4j repo. The majority of it is a 1:1 of hyperscan-java. Fair warning, my company (CarpeData) will be investing a lot of my time in improving it over the next couple weeks, so you may want to wait a bit until then as the quality should go up quite a bit.

As far as contributor access goes, I'll need a bit more time first to negotiate how much resources I can get from CarpeData to support the Chimera4j and get a better plan for what I want to do with Chimera4j. As soon as I figure out all that, I'd love to talk about what we could do to help bring the projects together given how similar they are!

**Comment by gliwka** [comment]
Sounds good :-) Talk to you soon.

**Comment by gliwka** [comment]
Updated dependency hyperscan to 5.1.1, 5.2.0 currently fails to build on linux as a shared library

**Comment by gliwka** [comment]
5.2.1 has been released fixing this issue.

**Comment by gliwka** [comment]
Implemented in https://github.com/gliwka/hyperscan-java/commit/954257f4b5fa0a4fc871cd57d1e96d4e1f078e00.
