### ISSUE TITLE
SIGSEGV during scan execution on Scanner class 

### ISSUE THREAD

**Issue by zcabh-21** [gliwka/hyperscan-java#71]
[This issue might be related to #8 ]

- We observe a segmentation fault when running an engine (a collection of hyperscan compiled regexes) on a specific host.
- SIGSEGV can manifest on the same host that performed the db compilation so it doesn't appear to be a matter of mismatched architectures.
- Full log: [hs_err_pid26287.log](https://github.com/gliwka/hyperscan-java/files/4331185/hs_err_pid26287.log)

**Comment by gliwka** [comment]
hyperscan-java on develop now uses JNI instead of JNA. The handling of native memory has changed significantly.

This issue should not occur anymore. Feel free to reopen it, if you encounter this issue again.
